### ISSUE TITLE
Peer dependency version of react is not the latest, so unable to install. Should it be compatible with 16?

### ISSUE THREAD

**Issue by karlbloedorn** [Shadowman4205/react-leaflet-curve#2]

**Comment by bmordan** [comment]
![screen shot 2018-10-11 at 15 55 08](https://user-images.githubusercontent.com/4499581/46813172-1eb3da00-cd6e-11e8-992c-b1e8d496de0a.jpg)

No.

**Comment by Shadowman4205** [comment]
@karlbloedorn  Check again please.
